### ISSUE TITLE
Update preferences

### ISSUE THREAD

**Issue by nofcfro** [pressidium/pressidium-cookie-consent#65] opened 2024-04-18 06:44 UTC
If a user wants to change the preferences chosen, how can he do it?
In other words, the user enters the site, and accepts all cookies, then has second thoughts, and wants to accept only the necessary cookies, what can he do?

**Comment by PriitGit** [comment] 2024-04-27 07:49
I have the same question?

**Comment by over-engineer** [comment] 2024-05-13 18:48
Hey, @nofcfro and @PriitGit!

This is on our radar in #24 and it’ll likely be included in the next plugin update.

Related issues
---

* #24
* #66

**Comment by over-engineer** [comment] 2024-05-13 18:48
Closing as a duplicate of #24.

**Closed by over-engineer** 2024-05-13 18:48 UTC
